### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by zvr** [eellak/build-recorder#190]
There should be tests for checking the correct build of the software.

Since the output is dependent on the environment, the check cannot be a simple 1:1 match; there must be some intelligence.

**Comment by fvalasiad** [comment]
@zvr do you expect something like:

```
hello-test.out: hello-test
cd @$
configure
make

hello-test:
git clone <url> hello-test
```

in the Makefile?

**Comment by zvr** [comment]
Closing this; #142 is already about tests
