### ISSUE TITLE
`build-recorder` build failure.

### ISSUE THREAD

**Issue by fvalasiad** [eellak/build-recorder#194]
Trying to build `build-recorder` in a clean install yields an error complaining that:

```
make[2]: ../build-recorder: No such file or directory
```

That is because `SUBDIRS` runs recursively depth first, and actually tries to run the test cases before `build-recorder` is built.

### Steps to reproduce
```
make clean
make
```

**Comment by fvalasiad** [comment]
@zvr What if we instead define a new rule "check" or whatever so that the examples are run solely when that rule is invoked?

```
make check
```

Toplevel makefile would then probably be:
```
ACLOCAL_AMFLAGS = -I m4

bin_PROGRAMS = build-recorder

build_recorder_SOURCES = \
    src/tracer.c \
    src/hash.c \
    src/record.c \
    src/main.c

SUBDIRS = benchmark

check:
    $(MAKE) -C examples
```

**Comment by zvr** [comment]
No. we don't want examples and benchmarks being run when building the software.

And you need them in `SUBDIRS` so that `automake` knows which directories to visit.
