### ISSUE TITLE
Output has to use the schema

### ISSUE THREAD

**Issue by zvr** [eellak/build-recorder#197]
The generated output RDF has to reference (or include) the schema.

**Comment by fvalasiad** [comment]
#178 Should also be merged given that the defined schema includes the size for each file, and yet `build-recorder(1)` does not really record it currently.

**Comment by fvalasiad** [comment]
@zvr Like, copy paste [/doc/build-recorder-schema.ttl](https://github.com/eellak/build-recorder/blob/main/doc/build-recorder-schema.ttl) at the start of the file? Or if a reference, like a link?
