### ISSUE TITLE
xxd -n option

### ISSUE THREAD

**Issue by fvalasiad** [eellak/build-recorder#214]
xxd fails because it does not recognize `-n schema`.

Failing to find any info on the web or manpage regarding that option, is it platform-specific?

I'd recommend instead letting it just print the values and then simply doing:

arr = { #include "schema.h" }

**Comment by fvalasiad** [comment]
@zvr Should I look for alternative POSIX defined ways to achieve the same result? Or even code it, it's relatively simple.

**Comment by fvalasiad** [comment]
@zvr Do I fix the above PR then and make sure the generated `schema.h` is included in the tarball?

**Comment by zvr** [comment]
Yes, please -- something like #213.
Submit a new PR and close the old one, there will be no relation in the code.

**Comment by zvr** [comment]
The _schema_ is included in the tarball.
The new PR should also add the generated `schema.c` in the tarball, so that people can compile the software without need to use `xxd`.

**Comment by fvalasiad** [comment]
Well looking around out of curiosity. https://github.com/vim/vim/commit/83e11800cc3775de3135ac7d823137c8c1e87fa1

It's a fairly recent addition, so my current OS based off of ubuntu jammy 22.04 does not include it. Debian 12 should have it though, it's only LTS versions that are impacted by this.
