### ISSUE TITLE
`build-recorder` executable placed under `src/` instead of toplevel.

### ISSUE THREAD

**Issue by fvalasiad** [eellak/build-recorder#216]
Uncertain if it's to be expected. Nevertheless benchmarks & examples depend on `build-recorder` being on the top-level dir, so unless fixed the user has to manually move the executable to top-level after building.

**Comment by Harshsaini001** [comment]
@fvalasiad I'm eager to tackle this issue. Could you please assign it to me so I can get started?

**Comment by fvalasiad** [comment]
@Harshsaini001 Hello, if zvr agrees that it's actually a problem, then sure! Remember: 

> Good Pull Requests (which contain patches, improvements, or new features) are always welcome!
> 
> Please ask first before embarking on any Pull Request, otherwise you risk spending time working on something that might not be merged into the project.
