### ISSUE TITLE
Changing the way `open(2)` is traced.

### ISSUE THREAD

**Issue by fvalasiad** [eellak/build-recorder#74]
@zvr As previously discussed, `open(2)`,`openat(2)`,`openat2(2)`,`open_tree(2)` and a couple of others are currently handled by converting their `path` argument to a `relative`. We've talked about how this is unsafe and that we should instead consider the following solution:

1. On `open(2)`, open a file descriptor in the tracer by opening `/proc/<pid>/fd/<fd>` and store it in `FILE_INFO`.
2. On `close(2)`, hash the file pointed by the tracer's open file descriptor,store the result and close the file descriptor.

This has the advantage that we are safe of any kind of concurrent file access, it also is much more generic and we won't have to create special handlers for the numerous variants of `open(2)`, some of which are pretty complicated.

Starting to look at how we should track `rename(2)` i can see that this approach would help us there too. Because there are also `rename(2)` variants such as `renameat(2)` and `renameat2(2)`. We could easily handle them all if we only had an array mapping the tracee's open file descriptors to our corresponding open file descriptors.

Thus i suggest we should make the switch.

**Comment by zvr** [comment]
Nice to explore...
but I'm not merging anything that is not a bug fix until we have something running completely, no matter the problems.

it's been 10 weeks since project start and we still haven't seen the results of a run.

**Comment by fvalasiad** [comment]
@zvr Well practically after we merge #58 and #75, we can start testing.

**Comment by fvalasiad** [comment]
Very outdated issue, the codebase has changed alot ever since, even though the changes described could be updated to fit the current codebase, I don't see any reason to do that currently and as a result I close this issue.
